.SILENT:

help:
	printf "Does all the things... \n"
	printf "make <rule> <optional path>"
	print  "add <blog_path> - adds/updates the blog in the database"
	print  "add <blog_path> - adds the blog to the database"